apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vmware_exporter
  annotations:
    github.com/project-slug: muravsky/vmware_exporter
    backstage.io/source-location: url:https://github.com/muravsky/vmware_exporter
    backstage.io/source-vcs: url:https://github.com/muravsky/vmware_exporter
spec:
  type: service
  lifecycle: production
  owner: muravsky
